---@class StaticMemory
local staticMock = {
    ---@class WorldMemory World space readings.
    ---@field Position vec3 The current construct position in world coordinates.
    ---@field Velocity vec3 The current construct velocity in world coordinates.
    ---@field Acceleration vec3 The current construct acceleration in world coordinates.
    ---@field Up vec3 The current construct up vector in world coordinates
    ---@field Forward vec3 The current construct forward vector in world coordinates.
    ---@field Right vec3 The current construct right vector in world coordinates.
    ---@field Gravity vec3 The current gravity vector in world coordinates and length as the acceleration in m/s.
    ---@field G number The current acceleration due to gravity in m/s.
    ---@field Vertical vec3 The current gravity vector as a unit vector.
    ---@field AirFriction vec3 The acceleration generated by air resistance.
    ---@field AtmosphericDensity number The local atmosphere density, between 0 and 1.
    ---@field VerticalVelocity number The acceleration along the gravity vector in m/s.
    ---@field AngularVelocity vec3 The constructs angular velocity, in world coordinates.
    ---@field AngularAcceleration vec3 The construct's angular acceleration, in world coordinates.
    ---@field AngularAirFriction vec3 The acceleration torque generated by air resistance.
    World = {},
    ---@class ShipMemory Construct readings.
    ---@field Altitude number Altitude above sea level, with respect to the closest planet (0 in space).
    ---@field Id integer Returns the construct unique ID.
    ---@field Mass number The mass of the construct.
    ---@field CrossSection number The construct's cross sectional surface in the current direction of movement in m^2. Note: Only defined for dynamic cores.
    ---@field MaxKinematics MaxKinematicsModel The maximum force which can be output for each direction.
    ---@field Yaw number The current yaw.
    ---@field Pitch number The current pitch.
    ---@field Roll number The current roll.
    Ship = {},
    ---@class LocalMemory Local space readings.
    ---@field Velocity vec3 Current velocity in local space.
    ---@field Acceleration vec3 Current acceleration in local space.
    Local = {}
}

---@class MaxKinematicsModel
---@field Forward number Maximum forward force in Newton.
---@field Backward number Maximum backwards force in Newton.
---@field Up number Maximum backward force in Newton.
---@field Down number Maximum downward force in Newton.
---@field Left number Maximum leftward force in Newton.
---@field Right number Maximum rightward force in Newton.

---@class KeybindEvent Keybind event model
local keybindEvent = {
    ---Event to be emitted on action
    "EventName",
    true
}